import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image/";
import Link from "next/link";
import { useState } from "react";
import { Tab, Tabs, Sonnet, Row, Col, Nav } from "react-bootstrap";
import { makeStyles } from "@material-ui/core/styles";
import Accordion from "@material-ui/core/Accordion";
import AccordionSummary from "@material-ui/core/AccordionSummary";
import AccordionDetails from "@material-ui/core/AccordionDetails";
import Typography from "@material-ui/core/Typography";
import ExpandMoreIcon from "@material-ui/icons/ExpandMore";
import axios from "axios";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Review from "../../components/Review";
import Timer from "../../components/Timer";
import router, { useRouter } from "next/router";
import Mobilemenu from "../../components/comps/Mobilemenu";
import { QuantityPicker } from "react-qty-picker";
import { useSelector, useDispatch } from "react-redux";
import Checkout from "../../components/checkout/Checkout";
import { addToCart } from "../../store/actions/cartActions";


const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
  },
  heading: {
    fontSize: theme.typography.pxToRem(15),
    fontWeight: theme.typography.fontWeightRegular,
  },
}));

let descolor = {
  color: "00b2bd ",
};
let imgStyle = {
  width: "100%",
  height: "300px",

  // backgroundColor: "#FFB900",
  paddingRight: "auto !important",
  paddingLeft: "auto !important",
};
let paddingP = {
  paddingTop: "8rem!important",
};
let headerButton = {
  border: "1px solid #1A4692",
  fontSize: "12px",
  width: "70px",
  height: "48px",
  color: "#1A4692",
  borderRadius: "5px",
};
let card = {
  padding: "8px",
  borderRadius: "8px",
  boxShadow: "7px 5px 19px -7px rgb(0 0 0 / 15%)",
};
let mainheading = {
  color: "#1A4692",
};
let heading = {
  fontSize: "15px",
};
let fa = {
  color: "red",
};
let deltext = {
  fontSize: "14px",
  color: "#7c7c7c",
};
let savetext = {
  fontSize: "14px",
  paddingLeft: "22px",
  color: "#00b2bd",
};
let sizetext = {
  fontSize: "10px",
  color: "#7c7c7c",
};
let button = {
  fontSize: "13px",
  color: "red",
  border: "2px solid grey",
  borderRadius: "4px",
  width: "170px",
};
let textwidth = {
  width: "1175px",
};
let titlebottomline = {
  display: "block",
  height: "2px",
  width: "73px",
  borderBottom: "2px solid grey",
  margin: "0 auto ",
};

function Headboardproduct ({ response }) {
  //ADD TO CART REDUX
  const dispatch = useDispatch();
  const [total, setTotal] = useState(0);
  const [qty, setQty] = useState(1);
  
  const addToCartHandler = () => {
    dispatch(addToCart(response[0]._id, parseInt(qty)));
    router.push("/cart");
  };

  async function addToCarsst() {
    // const { data } = await axios.get(`/api/products/${response[0]._id}`);

    console.log(data);
  }
  addToCarsst();
  const [expanded, setExpanded] = useState("panel1");
  const [data, setData] = useState([]);
  const [bed, setBed] = useState([]);
  const [color, setColor] = useState([]);
  const [image, setImage] = useState(
    "/assets/images/ProductImage/divan-grey-pic-new-1 (1).jpg"
  );
  const storageIcon = [
    "/assets/images/newicons/storage000-01.png",
    "/assets/images/newicons/Storage-03.png",
    "/assets/images/newicons/Storage-04.png",
  ];
  const storagetitle = ["2 Same Side", " 2Foot Side", "4 Drawer"];

  let storageindex = 0;

  const feetIcon = [
    "/assets/images/newicons/feets-01.png",
    "/assets/images/newicons/feets-02.png",
  ];
  let feetindex = 0;

  //STORING PRICE IN STATE
  const [headboard, setHeadboard] = useState(0);
  const [storage, setStorage] = useState(0);
  const [mattress, setMattress] = useState(0);
  const [feets, setfeet] = useState(0);


  console.log(total);
  console.log(headboard);
  console.log(mattress);
  console.log(storage);

  const handleChange = (panel) => (event, newExpanded) => {
    setExpanded(newExpanded ? panel : false);
  };

  const classes = useStyles({});

  //FETCHING API FOR BEDS

  useEffect(() => {
    setData(response);
    setBed(response[0]);
    // setColor(response[0].images[0].color1);
  }, [response]);
  useEffect(() => {
    setTotal(
      parseInt(qty) *
        (parseInt(bed?.price) +
          parseInt(headboard) +
          parseInt(storage) +
          parseInt(mattress) +
          parseInt(feets))
    );
  }, [response, headboard, storage, mattress, bed, feets, qty]);

  console.log(bed);
  return (
    <div>
      <div>
        <Head>
          <title>BedsDivans</title>
          <meta name="description" content="Generated by create next app" />
          <link
            passHref={true}
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          />

          <link
            passHref={true}
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          ></link>
          <link
            passHref={true}
            href="/style/plugins/plugins.min.css/"
            rel="stylesheet"
          ></link>
          <link passHref={true} rel="icon" href="/logo (1).png" />
        </Head>
        <div>
          <div className="fordesktopmeu">
            <Header />
          </div>

          <div className="mb-10 formobilemenu">
            <Mobilemenu />
          </div>

          <div className="container-fluid fluid-color tab-touch-section">
            <div className="container  tab-touch-cont">
              <div className="row">
                <div className="col-md-6 big-img-chenger">
                  <div className="twofeet">
                    <Timer />
                    <Image
                      id="shwimg_1"
                      className="imgfornone"
                      width={600}
                      height={550}
                      src={image}
                    />
                  </div>

                  {/* <Image width={100} height={100} id="shwimg_7" className="imgfornone"   src="/assets/images/image/meter.png"/> */}
                  {/* <Image src=""/> */}
                </div>
                <div className="col-md-6 mt-4 outer-tab-section">
                  <h5 className="HeadingProduct">
                    <b>{bed?.product_name}</b>
                  </h5>
                  <Image
                    src="/assets/images/image/trustpilot-5stars.png"
                    width={140}
                    height={30}
                  />
                  <span className="trustreview">
                    <b> ( 5,245,22 Reviews) </b>
                  </span>
                  <div className="mt-4 image-multitabs">
                    <Tab.Container
                      id="left-tabs-example"
                      defaultActiveKey="first"
                    >
                      <Row>
                        <Col sm={3} xs={12}>
                          <Nav variant="pills" className="flex-column">
                            <Nav.Item>
                              <Nav.Link eventKey="first"> Sizes</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                              <Nav.Link eventKey="second">Color</Nav.Link>
                            </Nav.Item>
                            
                          </Nav>
                        </Col>
                        <Col sm={9} col xs={12}>
                          <Tab.Content>
                            <Tab.Pane eventKey="first">
                              <div className="bg-white cusHeight Headboard-page">
                                <div className="row">
                                  <div className="col-md-12 mt-4 ml-6 ">
                                    {/* <Image
                                      width={40}
                                      height={50}
                                      src="/assets/images/image/meter.png"
                                    />
                                    <span className="cusSize">Bed Size </span> */}
                                    <span className="optionB">
                                      24 Option Available
                                    </span>{" "}
                                    <br />
                                    <hr
                                      style={{
                                        marginLeft: "-20px",
                                        width: "445px",
                                      }}
                                    />
                                  </div>
                                </div>
                                <div className="container-fluid slider-Mobile">
                                  <div className="row">
                                    <div
                                      className="col-md-3 productimghover"
                                      onClick={() => {
                                        var newarray = response?.filter(
                                          function (beds) {
                                            return beds.size === "2FT 6";
                                          }
                                        );
                                        setImage(
                                          newarray[0].images[0].color1.base_url
                                        );
                                        setBed(newarray[0]);
                                        console.log(bed);
                                      }}
                                    >
                                      <Image
                                        id="img_1"
                                        width={140}
                                        height={100}
                                        src="/assets/images/image/bed-sizes-01.png"
                                      />
                                      <br />
                                      <span className="productsize">
                                        2.6ft Single{" "}
                                        <span>
                                          {" "}
                                          <br /> <b> (£79)</b>
                                        </span>
                                      </span>
                                      <br />
                                      {/*<span className="productsize" style={{fontSize:"14px"}}> £ 400</span>*/}
                                    </div>
                                    <div
                                      className="col-md-3 productimghover"
                                      onClick={() => {
                                        var newarray = response?.filter(
                                          function (beds) {
                                            return beds.size === "3FT";
                                          }
                                        );
                                        setImage(
                                          newarray[0].images[0].color1.base_url
                                        );
                                        setBed(newarray[0]);
                                        console.log(bed);
                                      }}
                                    >
                                      <Image
                                        width={140}
                                        height={100}
                                        id="img_2"
                                        src="/assets/images/image/bed-sizes-02.png"
                                      />
                                      <span className="productsize">
                                        3ft Single{" "}
                                        <span>
                                          {" "}
                                          <br />
                                          <b> (£89) </b>
                                        </span>
                                      </span>
                                      <br />
                                      {/*<span className="productsize" style={{fontSize:"14px"}}> £ 400</span>*/}
                                    </div>
                                    <div
                                      className="col-md-3 productimghover"
                                      onClick={() => {
                                        var newarray = response?.filter(
                                          function (beds) {
                                            return beds.size === "4FT";
                                          }
                                        );
                                        setImage(
                                          newarray[0].images[0].color1.base_url
                                        );
                                        setBed(newarray[0]);
                                        console.log(bed);
                                      }}
                                    >
                                      <Image
                                        width={140}
                                        height={100}
                                        id="img_3"
                                        src="/assets/images/image/bed-sizes-03.png"
                                      />
                                      <span className="productsize">
                                        4ft Single{" "}
                                        <span>
                                          {" "}
                                          <br /> <b> (£109)</b>
                                        </span>
                                      </span>
                                      <br />
                                      {/*<span className="productsize" style={{fontSize:"14px"}}> £ 400</span>*/}
                                    </div>
                                    <div
                                      className="col-md-3 productimghover"
                                      onClick={() => {
                                        var newarray = response?.filter(
                                          function (beds) {
                                            return beds.size === "4FT 6";
                                          }
                                        );
                                        setImage(
                                          newarray[0].images[0].color1.base_url
                                        );
                                        setBed(newarray[0]);
                                        console.log(bed);
                                      }}
                                    >
                                      <Image
                                        id="img_4"
                                        width={140}
                                        height={100}
                                        src="/assets/images/image/bed-sizes-04.png"
                                      />
                                      <span className="productsize">
                                        4.6ft Single{" "}
                                        <span>
                                          {" "}
                                          <br /> <b> (£109) </b>
                                        </span>
                                      </span>
                                      <br />

                                      {/*<span className="productsize" style={{fontSize:"14px"}}> £ 400</span>*/}
                                    </div>
                                    {/* <div className="container-fluid">
                                  <div className="row mt-2"> */}
                                    <div
                                      className="col-md-3   productimghover"
                                      onClick={() => {
                                        var newarray = response?.filter(
                                          function (beds) {
                                            return beds.size === "5FT";
                                          }
                                        );
                                        setImage(
                                          newarray[0].images[0].color1.base_url
                                        );
                                        setBed(newarray[0]);
                                        console.log(bed);
                                      }}
                                    >
                                      <Image
                                        id="img_5"
                                        width={140}
                                        height={100}
                                        src="/assets/images/image/bed-sizes-05.png"
                                      />
                                      <span className="productsize">
                                        5ft Single{" "}
                                        <span>
                                          {" "}
                                          <br /> <b> (£119)</b>
                                        </span>
                                      </span>
                                      <br />
                                      {/*<span className="productsize" style={{fontSize:"14px"}}> £ 400</span>*/}
                                    </div>
                                    <div
                                      className="col-md-3 productimghover"
                                      onClick={() => {
                                        var newarray = response?.filter(
                                          function (beds) {
                                            return beds.size === "6FT";
                                          }
                                        );
                                        setImage(
                                          newarray[0].images[0].color1.base_url
                                        );
                                        setBed(newarray[0]);
                                        console.log(bed);
                                      }}
                                    >
                                      <Image
                                        id="img_6"
                                        width={140}
                                        height={100}
                                        src="/assets/images/image/bed-sizes-06.png"
                                      />
                                      <span className="productsize">
                                        6ft Single{" "}
                                        <span>
                                          {" "}
                                          <br /> <b> (£149) </b>
                                        </span>
                                      </span>
                                      <br />
                                      {/*<span className="productsize" style={{fontSize:"14px"}}> £ 400</span>*/}
                                    </div>
                                    {/* <div className="col-md-3 mt-4  ">
        <Image width={100} height={80} src="/assets/images/image/box-image.png"/>

    </div> */}
                                    {/* <div className="col-md-3 mt-4  ">
        <Image width={100} height={80} src="/assets/images/image/box-image.png"/>

    </div> */}{" "}
                                  </div>
                                </div>
                                {/* </div> */}
                                {/* </div> */}
                                {/* <div className="container-fluid">

              
<div className="row">
    <div className="col-md-3 mt-4 ">
        <Image width={100} height={80} src="/assets/images/image/box-image.png"/>

    </div>
    <div className="col-md-3 mt-4  ">
        <Image width={100} height={80} src="/assets/images/image/box-image.png"/>

    </div>
    <div className="col-md-3 mt-4  ">
        <Image width={100} height={80} src="/assets/images/image/box-image.png"/>

    </div>
    <div className="col-md-3 mt-4  ">
        <Image width={100} height={80} src="/assets/images/image/box-image.png"/>

    </div>
</div>
</div> */}
                              </div>
                            </Tab.Pane>
                            <Tab.Pane eventKey="second">
                              <div className="bg-white cusHeight Headboard-page">
                                <div className="row">
                                  <div className="col-md-12 mt-4 ml-6">
                                    {/* <Image
                                      width={40}
                                      height={50}
                                      src="/assets/images/image/meter.png"
                                    />
                                    <span className="cusSize">Choose Size</span>*/}
                                    <span className="optionB">
                                      24 Option Available
                                    </span>{" "}
                                    <br />
                                    <hr
                                      style={{
                                        marginLeft: "-20px",
                                        width: "445px",
                                      }}
                                    />
                                  </div>
                                </div>
                                <div className="container-fluid slider-Mobile">
                                  <div className="row">
                                    <div
                                      className="col-md-3  productimghover"
                                      onClick={() => {
                                        setImage(
                                          bed?.images[0].color1.base_url
                                        );
                                        setColor(bed?.images[0].color1);
                                      }}
                                    >
                                      <Image
                                        id="img_7"
                                        width={60}
                                        height={60}
                                        src="/assets/images/image/123.jpg"
                                        className="colorImgR"
                                      />
                                      <br />
                                      <span className="productcolor">
                                        Grey Linen
                                      </span>
                                    </div>
                                    <div
                                      className="col-md-3  productimghover "
                                      onClick={() => {
                                        setImage(
                                          bed?.images[0].color2.base_url
                                        );
                                        setColor(bed?.images[0].color2);
                                      }}
                                    >
                                      <Image
                                        id="img_8"
                                        width={60}
                                        height={60}
                                        src="/assets/images/image/124.jpg "
                                        className="colorImgR"
                                      />
                                      <br />
                                      <span className="productcolor text-center">
                                        Grey Suede
                                      </span>
                                    </div>
                                    <div
                                      className="col-md-3  productimghover "
                                      onClick={() => {
                                        setImage(
                                          bed?.images[0].color3.base_url
                                        );
                                        setColor(bed?.images[0].color3);
                                      }}
                                    >
                                      <Image
                                        id="img_9"
                                        width={60}
                                        height={60}
                                        src="/assets/images/image/173.jpg"
                                        className="colorImgR"
                                      />
                                      <br />
                                      <span className="productcolor">
                                        Chennilie
                                      </span>
                                    </div>
                                    <div
                                      className="col-md-3   productimghover "
                                      onClick={() => {
                                        setImage(
                                          bed?.images[0].color4.base_url
                                        );
                                        setColor(bed?.images[0].color4);
                                      }}
                                    >
                                      <Image
                                        id="img_10"
                                        width={60}
                                        height={60}
                                        src="/assets/images/image/125.jpg"
                                        className="colorImgR"
                                      />
                                      <br />
                                      <span className="productcolor">
                                        Black Crushed
                                      </span>
                                    </div>
                                  </div>
                                </div>
                                <div className="container-fluid">
                                  {/* <div className="row">
    <div className="col-md-3  mt-2 productimghover ">
        <a href="">
        <Image id="img_11" width={60} height={60} src="/assets/images/image/173.jpg" className="colorImgR"/>
        <span className="productcolor" >Grey Seude   </span> 
        </a>
    </div>
    <div className="col-md-5 mt-2 productimghover">
        <a href="">
    <Image id="img_12" width={60} height={60} src="/assets/images/image/173.jpg" className="colorImgR"/> <br />
    <span className="productcolor" >Charcoal Chenille</span> 
    </a>
    </div>
     
</div> */}
                                </div>
                              </div>
                            </Tab.Pane>
                            
                          </Tab.Content>
                        </Col>
                      </Row>
                    </Tab.Container>
                  </div>

                  <div className="container price-touch-tab">
                    <div className="row">
                      <div className="col-md-3 col-xs-3 price-input">
                        
                        <QuantityPicker
                          min={1}
                          onChange={(e) => setQty(e)}
                          value={qty}
                        />

                        
                      </div>
                      <div className="col-md-9 col-xs-9 price-box">
                        <div className="scndbtn">
                          <div className="row">
                            <div className="col-md-6">
                              <h6
                                style={{
                                  color: "#7c7c7c",
                                  textAlign: "right",
                                  position: "relative",
                                  left: "-6px",
                                  top: "14px",
                                }}
                              >
                                <blockquote>WAS: £549.00</blockquote>
                              </h6>
                              <h2
                                style={{
                                  color: "red",
                                  position: "relative",
                                  left: "43px",
                                }}
                              >
                                <span
                                  style={{ fontSize: "12px", color: "#7c7c7c" }}
                                >
                                  <b>NOW: </b>
                                </span>
                                <b>
                                  £<span id="price_now">{total}</span>
                                </b>
                              </h2>
                            </div>
                            <div className="col-md-6">
                              
                              <Checkout addToCartHandler={addToCartHandler} price={total}/>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
         

          <Footer />
        </div>
      </div>
    </div>
  );
}

export default Headboardproduct;

export async function getServerSideProps(context) {
  const { req } = context;

  const title = req?.__NEXT_INIT_QUERY?.title;
  console.log(req);
  console.log(title);

  const data = await axios.post(
    "https://staggingx.bedsdivans.co.uk/api/products/getbeds",
    {
      method: "product_name",
      value: title,
    }
  );

  const response = await data.data.data;

  console.log(response);

  return {
    props: { response }, // will be passed to the page component as props
  };
}
